[OHFJIRA-106] : Circuit breaker
OpenWiseSolutions/openhub-framework pull request #101
Opened 2019-07-10 20:20 UTC by kkovarik

## Circuit breaker

Documentation : https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/1177288705/circuit
Please let me know what parts of it should be improved in any way, thanks!

Part of this pull request is camel component itself & two implementations of CircuitBreaker interface. Both are mentioned in documentation, one is in-memory, second is hazelcast based. There are three commits, as it may be quite a lot of code for one PR.

### Open questions
* name of the component - should it be `circuit` or `circuit-breaker`? currently it is circuit, to avoid boiler plate, as while used it can easily become quite unreadable: `circuit:my-system:http4://www.my-system.com/resource?method=POST&timeout=40000...`
* shouldn´t the configuration of component be more "camel-like", meaning it would parse uri and not to use the exchange property?

### Possible improvements
* currently only one implementation of CircuitBreaker interface is active for all circuits, technically it could be modified, that each circuit could have its own

2019-07-21 15:27 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitDownException.java
> +public class CircuitDownException extends RuntimeException {
Muze to dedit od IntegrationException?

2019-07-21 15:33 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/circuitbreaker/CircuitState.java
> +    private List<Long> successCallList = new CopyOnWriteArrayList<>();
Neni to zbytecny komfort pouzivat CopyOnWriteArrayList? Chapu, ze ti to vyresi problem s pristupem pres get() ke kolekci, ale trpi tim performance a mozna zbytecne. Davam k uvaze ...

2019-07-29 06:18 UTC, pjuza requested changes

2019-07-29 06:18 UTC, pjuza commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitComponent.java
> +        final String endpointURI = ObjectHelper.after(uri, ":");
IDE me ukazuje, ze ObjectHelper je deprecated, ze mas pouzit StringHelper

2019-07-29 06:18 UTC, pjuza commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitComponent.java
> +package org.openhubframework.openhub.component.circuitbreaker;
pridal bych sem i do jinych novych baliku packe-info.java

2019-07-29 06:18 UTC, pjuza commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitProducer.java
> +        Assert.notNull(circuitConfiguration, "the circuitConfiguration was not set.");
Asi bych jeste pridal info, ze neni nastaveno v Exchange + nazev te property, protoze preci jen to je trochu nestandardni, takze tato chyba bude vylitavat casto :)

2019-07-29 06:18 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitBreaker.java
> + * .doTry()
chtelo by to nejake formatovace do javaDoc, jinak je pak vse na jednom radku.

2019-07-29 06:18 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitBreaker.java
> +        Assert.notNull(circuitConfiguration, "the circuitConfiguration was not found");
tady bych tu chybovou hlasku take rozsiril ...

2019-07-29 06:18 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitConfiguration.java
> +    private String circuitName;
zadny konstruktor? mozna jemn nastavit nejaky default circuitName ...

2019-07-29 06:18 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/circuitbreaker/AbstractCircuitBreaker.java
> +package org.openhubframework.openhub.core.circuitbreaker;
pridal bych package-info.java

2019-09-09 16:33 UTC, kkovarik commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitDownException.java
> +public class CircuitDownException extends RuntimeException {
Tak asi by mohlo. IntegrationException by měly být všechny vyjímky z "vnitřku" OpenHubu? :)

2019-09-09 16:55 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/circuitbreaker/CircuitState.java
> +    private List<Long> successCallList = new CopyOnWriteArrayList<>();
Dobrá připomínka, vzniklo to při implementaci InMemory varianty. Možná opravdu zbytečné, upravím a doplním komentářem

2019-09-09 17:00 UTC, kkovarik commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitComponent.java
> +        final String endpointURI = ObjectHelper.after(uri, ":");
upraveno, díky

2019-09-09 17:02 UTC, kkovarik commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitComponent.java
> +package org.openhubframework.openhub.component.circuitbreaker;
Díky za upozornění, přidal jsem kde jsem našel

2019-09-09 17:04 UTC, kkovarik commented on components/src/main/java/org/openhubframework/openhub/component/circuitbreaker/CircuitProducer.java
> +        Assert.notNull(circuitConfiguration, "the circuitConfiguration was not set.");
Určitě, dobrý tip 👍 
Doplněno.

2019-09-09 17:12 UTC, kkovarik commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitBreaker.java
> + * .doTry()
upraveno, díky za upozornění

2019-09-09 17:13 UTC, kkovarik commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitBreaker.java
> +        Assert.notNull(circuitConfiguration, "the circuitConfiguration was not found");
done

2019-09-09 17:16 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/circuitbreaker/AbstractCircuitBreaker.java
> +package org.openhubframework.openhub.core.circuitbreaker;
přidáno

2019-09-10 06:41 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitDownException.java
> +public class CircuitDownException extends RuntimeException {
Ano, myslim, ze takova byla/je puvodni predstava. https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/33595/Error+handling

2019-09-10 20:50 UTC, kkovarik commented on core-spi/src/main/java/org/openhubframework/openhub/spi/circuitbreaker/CircuitDownException.java
> +public class CircuitDownException extends RuntimeException {
Supr, díky, upraveno :)

2019-09-11 07:42 UTC, pjuza approved these changes
Super, thank you for changes.

Please look at Sonar issues (https://sonarcloud.io/dashboard?id=OpenWiseSolutions_openhub-framework&pullRequest=101) if something is useful for you before final finishing.

2019-11-10 07:51 UTC, merged