Feature/ohfjira 19
OpenWiseSolutions/openhub-framework pull request #12
Opened 2017-01-18 17:47 UTC by openhubframework

2017-01-18 18:39 UTC, hanusto requested changes
From my side, it is necessary to do:

1) read contribution notes - https://openhubframework.atlassian.net/wiki/display/OHF/Contribution
2) read contribution rules and principles - https://openhubframework.atlassian.net/wiki/display/OHF/Rules+and+principles
3) for all java based files please change version to 2.0.0 (next release version will be 2.0.0)
4) please avoid to use full author tag (do not add e-mail address)
5) it is necessary to rebase these commits on to develop and solve some conflicts
6) please improve title and description of this PR
7) it is possible to squash all commits together?

After I can continue in review.

2017-01-30 17:38 UTC, hanusto requested changes
Basically everything is ok, but some questions is added. The biggest problem is formatting of imports. Please check https://openhubframework.atlassian.net/wiki/display/OHF/Source+code+conventions#Sourcecodeconventions-Javaimports and configure you IDE and reformat concerned classes.

2017-01-30 17:38 UTC, hanusto commented on components/src/main/java/org/openhubframework/openhub/component/asynchchild/AsynchChildProducer.java
> +import java.util.Arrays;
I dont understand why imports were re-ordered. Please consider https://openhubframework.atlassian.net/wiki/display/OHF/Source+code+conventions#Sourcecodeconventions-Javaimports.

2017-01-30 17:38 UTC, hanusto commented on components/src/test/java/org/openhubframework/openhub/component/asynchchild/AsynchChildComponentTest.java
> +import static org.junit.Assert.assertThat;
I dont understand why imports were re-ordered. Please consider https://openhubframework.atlassian.net/wiki/display/OHF/Source+code+conventions#Sourcecodeconventions-Javaimports (as previous comment).

2017-01-30 17:38 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/msg/ChildMessage.java
> +import java.util.UUID;
I dont understand why imports were re-ordered. Please consider https://openhubframework.atlassian.net/wiki/display/OHF/Source+code+conventions#Sourcecodeconventions-Javaimports (as previous comment).

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/AsynchMessageRoute.java
> +                    // forcefully mark current external call as unsuccessful
It should be change back.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/AsynchMessageRoute.java
> +                .validate((Predicate) simple("${body.state} == 'IN_QUEUE'"))
Why `MsgStateEnum` is not used?

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/AsynchMessageRoute.java
> +        Log.debug("Change state of message '" + msg.toHumanString() + "' into '" + MsgStateEnum.IN_QUEUE + "'");
Why `Log.debug("Change state of message '{}' into '{}'", msg.toHumanString(), MsgStateEnum.IN_QUEUE);` is not used?

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
> +        Assert.state(message.getState().equals(MsgStateEnum.NEW)
Maybe we can add method `#canBeAddedToQueue` (or similar which reflects functionality) to `Message` class? Behaviour will be encapsulated.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
> +            Log.debug("Failed to lock message: {} for change state", message.getMsgId(), MsgStateEnum.IN_QUEUE);
This is wrong. You have two arguments but only one placeholder.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
> +            Log.debug("Failed to lock message: {} for change state", message.getMsgId(), MsgStateEnum.PROCESSING);
This is wrong. You have two arguments but only one placeholder.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
> +    public void setTransactionManager(JpaTransactionManager transactionManager) {
Why setter injection is used? To achieve correct behaviour it is necessary to correctly setup transaction template. I think it should be in constructor, so constructor inject is better choice.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/MessagePollExecutor.java
> +    private String targetURI = AsynchMessageRoute.URI_ASYNC_PROCESSING_MSG;
Maybe `URI_ASYNC_PROCESSING_MSG` should be constant on `AsynchConstants`, not on `AsynchMessageRoute`.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/MessagesPoolDbImpl.java
> +    private MessageService messageService;
I don't understand this approach. This class autowires `MessageDao` and also `MessageService`? What is reason?

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/MessageDaoJpaImpl.java
> +            q.setLockMode(LockModeType.PESSIMISTIC_WRITE);
One question = is there place where timeout for lock is specified? I mean `javax.persistence.lock.timeout` to avoid dead locks.

2017-01-30 17:38 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/MessageDaoJpaImpl.java
> +                + "WHERE (m.state = '" + MsgStateEnum.PROCESSING
I think that we should rewrite this very complicated query to criteria API.

2017-01-30 17:38 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/common/asynch/AsynchInMessageRouteTest.java
> +@ActiveRoutes(classes = {AsynchInMessageRoute.class})
It is not necessary to use braces

2017-01-30 17:38 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/common/asynch/AsynchInMessageRouteTest.java
> +    public void prepareData() throws Exception{
space between `Exception` and `{`

2017-01-30 17:38 UTC, hanusto commented on pom.xml
> +                <version>4.0</version>
I recommend to use maven property to define version of apache common collections 4. For which use case is used? This dependency is marked by OWASP that contains security vulnerability.

2017-01-31 17:33 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/msg/MessageServiceImpl.java
> +        Assert.state(message.getState().equals(MsgStateEnum.NEW)
Add method #canBeAddedToQueue method on Message is not good solution. Better solution is create truly workflow function for Message entity. We have created isssue on that.

2017-02-03 16:51 UTC, hanusto commented
It is ready to review?

2017-02-05 12:03 UTC, hanusto approved these changes
From my site, it looks good.

2017-02-05 12:30 UTC, merged