[OHFJIRA-85]: Upgrade to Spring Boot 2.0.9.RELEASE
OpenWiseSolutions/openhub-framework pull request #129
Opened 2021-02-04 14:46 UTC by jhankovec

<h3>Upgrade spring boot version to 2.0.9.</h3>
<p><ul><li>Migration from spring boot 1.5.22. to 2.0.9. - <a href="https://openhubframework.atlassian.net/browse/OHFJIRA-85">https://openhubframework.atlassian.net/browse/OHFJIRA-85</a></li><li>Update camel version to 2.22.2 due to <a href="https://github.com/camel-tooling/generator-camel-project/issues/43">https://github.com/camel-tooling/generator-camel-project/issues/43</a></li><li>New Flyway migration strategy for tests (first clean DB then migrate)</li><li>Custom actuator endpoint for metrics.</li></ul></p>

<p>Spring boot 2.0 release notes - <a href="https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes">https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes</a> and migration guide <a href="https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide">https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide</a></p>

2021-02-18 13:06 UTC, hanusto commented
Please could you provide link to our documentation with description what is need to take account if some wants to migrate OHF itself?

2021-02-18 13:20 UTC, hanusto requested changes
Please fix my notes.

2021-02-18 13:20 UTC, hanusto commented on pom.xml
> +        <hazelcast-version>3.9.4</hazelcast-version>
Under 2.4.3 spring boot there is 4.0.3 version of hazelcast (https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.4.2). It should be in BOM POM of Spring Boot itself. Maybe we don't have to define specific version, don't it?

2021-02-18 13:20 UTC, hanusto commented on pom.xml
> +                <version>${janino.version}</version>
3.1.2 in BOM POM. We should use version of libs from BOM POM of Spring Boot.

2021-02-18 13:20 UTC, hanusto commented on web/pom.xml
> +            <groupId>javax.validation</groupId>
it is probably transitive dependency of org.hibernate.validator? So we can omit that.

2021-02-18 13:20 UTC, hanusto commented on web/src/main/resources/application.properties
> +logging.file.name=openhub.log
Please can you check our documentation if properties which had to be changed are correct?

2021-02-18 13:20 UTC, hanusto commented on web/src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
It can be maybe only in test scope, right?

2021-02-18 13:20 UTC, hanusto commented on admin-console/mock-server/health/health.mock.js
> +          'components': {
All changes in health/metrics endpoints should be somehow document in migration guide to this version. It is very important from operations point of view (and migration as well).

2021-02-18 13:37 UTC, hanusto requested changes
Check please my remarks.

2021-02-18 13:37 UTC, hanusto commented on admin-console/src/services/home.service.js
> +  getMetrics: '/mgmt/ohfmetrics'
Question. We prepared our ohfmetrics endpoint for our application but we changed client as well. Why? I thought that we have two options - 1) our custom endpoint without impact to client (web gui) or 2) migration client app to updated version of metrics endpoint.

2021-02-18 13:37 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/common/asynch/queue/MessagePollExecutorTest.java
> +    //TODO Jiri Hankovec 4.2.2021
Please can you write some notes to this TODO why these tests have to be ignored? And we should create JIRA issue and link that to these code lines.

2021-02-18 13:37 UTC, hanusto commented on pom.xml
> +                     <!-- compiler is disabled because of aspectj compiler -->
Leave unchanged line.

2021-02-18 13:37 UTC, hanusto commented on pom.xml
> +                        <!--<aggregate>true</aggregate>-->
It is not problem for javadoc generation itself? Check this - https://openwisesolutions.github.io/openhub-framework/docs/current/javadoc-api/. It is automatic process of generation and result should be the same.

If aggregation is not required we can remove this commented line.

2021-02-18 13:37 UTC, hanusto commented on pom.xml
> +                        <doclint>none</doclint>
The same as above.

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/admin/config/AdminMvcConfig.java
> +//        Resource page = this.resourceProperties.getWelcomePage();
Please remove commented code.

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/admin/config/OhfMetricsConfiguration.java
> +@AutoConfiguration
added "author" block code.

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/admin/web/metrics/OhfMetricsEndpoint.java
> +@WebEndpoint(id = "ohfmetrics")
Is it possible to use /mgmt/ohg/metrics or something like that?

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/admin/web/metrics/OhfMetricsEndpoint.java
> +public class OhfMetricsEndpoint {
Is it needed to create custom metrics endpoint when we had to update GUI client anyway?

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/web/config/WebSecurityConfig.java
> +//        @Autowired
Leave commented line please.

2021-02-18 13:37 UTC, hanusto commented on web/src/main/java/org/openhubframework/openhub/web/config/WebSecurityConfig.java
> +        /*private AuthenticationEntryPoint basicAuthenticationEntryPoint() {
Remove commented line.

2021-02-18 13:37 UTC, hanusto commented on web/src/main/resources/application-postgresql.properties
> +#spring.datasource.initialize=false
Correct is "spring.datasource.initialization-mode". So we can comment that but property name should be correct.

2021-02-18 14:56 UTC, sabolm reviewed
Check minor improvements.

2021-02-18 14:56 UTC, sabolm commented on web/src/main/java/org/openhubframework/openhub/admin/config/OhfMetricsConfiguration.java
> +@AutoConfiguration
also please add documentation.

2021-02-18 14:56 UTC, sabolm commented on web/src/main/java/org/openhubframework/openhub/web/common/OhfBasicAuthenticationEntryPoint.java
> +@Component
Please add documentation.

2021-02-18 14:56 UTC, sabolm commented on web/src/main/java/org/openhubframework/openhub/web/common/OhfBasicAuthenticationEntryPoint.java
> +import javax.servlet.ServletException;
unused import

2021-02-18 14:56 UTC, sabolm commented on common/src/main/java/org/openhubframework/openhub/common/properties/OpenHubExternalPropertiesAutoConfiguration.java
>  import org.springframework.boot.context.config.ConfigFileApplicationListener;
Deprecated since 2.4.0

2021-05-20 11:56 UTC, hanusto approved these changes

2021-05-20 12:04 UTC, hanusto commented on pom.xml
> +        <hazelcast-version>3.9.4</hazelcast-version>
Previous version of hazelcast is 3.9 and there are many changes so we created issue - https://openhubframework.atlassian.net/browse/OHFJIRA-117.

2021-05-20 12:07 UTC, hanusto commented on common/src/main/java/org/openhubframework/openhub/common/properties/OpenHubExternalPropertiesAutoConfiguration.java
>  import org.springframework.boot.context.config.ConfigFileApplicationListener;
ConfigDataEnvironmentPostProcessor is used now

2021-05-20 14:47 UTC, merged