Feature/ohfjira 14
OpenWiseSolutions/openhub-framework pull request #13
Opened 2017-01-18 17:47 UTC by openhubframework

2017-01-18 18:38 UTC, hanusto requested changes
From my side, it is necessary to do:

1) read contribution notes - https://openhubframework.atlassian.net/wiki/display/OHF/Contribution
2) read contribution rules and principles - https://openhubframework.atlassian.net/wiki/display/OHF/Rules+and+principles
3) for all java based files please change version to 2.0.0 (next release version will be 2.0.0)
4) please avoid to use full author tag (do not add e-mail address)
5) it is necessary to rebase these commits on to develop and solve some conflicts
6) please improve title and description of this PR
7) it is possible to squash all commits together?

After I can continue in review.

2017-01-18 19:45 UTC, pjuza reviewed
Please add summary of what is going on in this task (https://openhubframework.atlassian.net/browse/OHFJIRA-14) - we know problem and it's necessary to add task description, what is implemented

2017-01-18 19:45 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationBlock.java
> + * Method {@link #doInSynchronizationPart()} in this interface can be synchronized by one one value in
mistake "one one"

2017-01-18 19:45 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationExecutor.java
> + * Executor for {@link SynchronizationBlock} which synchronized more then one threads by one value.
which -> that

2017-01-18 19:45 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationExecutor.java
> + * {@link SynchronizationBlock#doInSynchronizationPart()} are code which will be by synchronized by value.
which -> that + will be synchronized by value

2017-01-18 19:55 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationNoResultBlock.java
> +    protected abstract void doInSynchronizationPartNoResult();
When the class has name SynchronizationNoResultBlock then method could be shorter, for example doInSynchro or synchroBlock ...

2017-01-18 19:55 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationExecutor.java
> + * </p>
Little bit more <p> :)

2017-01-19 11:42 UTC, hanusto commented
Maybe we should consider new PR in Camel Core:

- https://github.com/apache/camel/pull/1404
- https://github.com/apache/camel/pull/1400 ([ThrottlingExceptionRoutePolicy](https://github.com/apache/camel/pull/1400/files#diff-033333669cf0e63ff86d4fe88d2eae7fR52))

2017-01-30 17:51 UTC, hanusto requested changes
Small changes are necessary (reformat code) and consider if lazy loaded singleton is necessary. After clarification it can be approved (merged).

2017-01-30 17:51 UTC, hanusto commented on common/src/main/java/org/openhubframework/openhub/common/synchronization/SynchronizationExecutor.java
> +    public synchronized static SynchronizationExecutor getInstance() {
Synchronization of lazy loaded singleton is broken. Please you static eager initialization - http://www.javaworld.com/article/2074979/java-concurrency/double-checked-locking--clever--but-broken.html?page=2.

2017-01-30 17:51 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/throttling/ThrottleCounterMemoryImpl.java
> +    private static final String SYNC_THROTTLING_TYPE = "SYNCHRONIZATION_THROTTLING";
Maybe `THROTTLING_SYNCHRONIZATION` is better name.

2017-01-30 17:51 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/throttling/ThrottleCounterMemoryImpl.java
> +                long now = DateTime.now().getMillis();
We use spaces for indent, no tabs - see https://openhubframework.atlassian.net/wiki/display/OHF/Source+code+conventions#Sourcecodeconventions-Syntaxrules.

2017-01-30 18:42 UTC, hanusto approved these changes

2017-01-30 19:22 UTC, merged