Added Authentication
OpenWiseSolutions/openhub-framework pull request #17
Opened 2017-01-21 10:25 UTC by bionaut

- new mock server
- login mocks
- login modal and form

2017-01-21 10:36 UTC, pjuza approved these changes

2017-01-24 11:34 UTC, hanusto requested changes
Please only one change is necessary:

Rewrite `#submitLogin` function:

```
export function submitLogin ({ username, password }) {
  // we have to use application/x-www-form-urlencoded
  const params = new URLSearchParams()
  params.append('username', username)
  params.append('password', password)
  // todo API constants ?
  const payload = axios.post('/login', params)
  return {
    type: SUBMIT_LOGIN,
    payload
  }
}
```

2017-01-24 11:34 UTC, hanusto commented on admin-console/src/common/actions/auth.actions.js
> +  // todo API constants ?
Please could you change content type to `application/x-www-form-urlencoded`? Because now we want to support current and new console together therefore we have to use API without change.

Following snippet works correctly:
```
  // we have to use application/x-www-form-urlencoded
  const params = new URLSearchParams()
  params.append('username', username)
  params.append('password', password)
  // todo API constants ?
  const payload = axios.post('/login', params)
  return {
    type: SUBMIT_LOGIN,
    payload
  }
```

To logout, it is possible via `/logout` URL. Just call it.

When new admin console will be completely done, authentication process will use OAuth with [self-hosted OAuth2 Authorization Server](https://spring.io/guides/tutorials/spring-boot-oauth2/).

2017-02-01 10:06 UTC, hanusto approved these changes

2017-02-01 10:07 UTC, merged