Feature/ohfjira 26 refine config
OpenWiseSolutions/openhub-framework pull request #18
Opened 2017-01-23 09:35 UTC by pjuza

2017-01-23 12:47 UTC, hanusto requested changes
I reviewed this PR. I think all is good, only small improvements to do added. Maybe one question is different - what is recommended way to define custom spring profiles? By current implementation of loading `openhub.properties` it is not possible.

2017-01-23 12:47 UTC, hanusto commented on components/src/test/java/org/openhubframework/openhub/component/ComponentTestConfig.java
> +@PropertySource(value = {"classpath:/config/application-test-default.properties"})
This is because since a property file application-test represents configuration of application with activated spring `test` profile, but this property file already exists, right? Maybe we can add some comment...

2017-01-23 12:47 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +     * FailedCount of partly fails before message will be marked as completely FAILED.
`FailedCount` -> Filed count

2017-01-23 12:47 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +
Remote unnecessary line please or it is intention?

2017-01-23 12:47 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/AsynchConstants.java
> +            + "?concurrentConsumers={{" + ASYNCH_CONCURRENT_CONSUMERS + "}}&waitForTaskToComplete=Never"
Are you sure that this is correct? When camel context and `seda` is initialized, change of `ASYNCH_CONCURRENT_CONSUMERS` will not take into account. Maybe we should remove this property from DB configuration layer into "only" properties layer. Or is there another way how we can dynamically change "size" of seda?

2017-01-23 12:47 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/alerts/AlertsPropertiesConfiguration.java
> +        for (String propName : Tools.getAllKnownPropertyNames((ConfigurableEnvironment)env)) {
Why casting is used? Maybe we should autowire a type safe interface.

2017-01-23 12:47 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/directcall/DirectCallHttpImpl.java
> +        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
👍

2017-01-23 12:47 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/directcall/DirectCallHttpImpl.java
>                      if (status >= 200 && status < 300) {
Maybe we can use HttpStatus enum - `org.springframework.http.HttpStatus`

2017-01-23 12:47 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    /**
Maybe one extra PREFIX_CONSTANT can be added for reuse:
```
public static final String PREFIX = "ohf.";
```

2017-01-23 12:47 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/confcheck/ConfigurationChecker.java
> +     * Checks if configuration parameter "ohf.server.localhostUri" is valid - calls PING service.
In cluster environment, which URL will be used?

2017-01-23 12:47 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/configuration/FileExternalPropertiesAutoConfiguration.java
> +public class FileExternalPropertiesAutoConfiguration
I see one problem of this solution - `spring.profiles.active` property is always resolved previously, so via openhub.properties there is probably no way how to setup custom spring profiles. When user of OHF needs to define own spring profiles he has to use `/config/application.properties` or JVM arguments. The same is for `spring.profiles.include`. Or maybe solution is to change behaviour of `org.springframework.boot.context.config.ConfigFileApplicationListener#addPropertySources`.

2017-01-23 12:47 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/configuration/FileExternalPropertiesAutoConfigurationTest.java
> +public class FileExternalPropertiesAutoConfigurationTest extends AbstractCoreDbTest {
I think that this UC is not testing `FileExternalPropertiesAutoConfigurationTest`, it tests only external configuration model.

2017-01-23 12:47 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/configuration/FileExternalPropertiesAutoConfigurationTest.java
> +public class FileExternalPropertiesAutoConfigurationTest extends AbstractCoreDbTest {
Sorry, i have seen core/src/test/resources/openhub.properties :)

2017-01-23 16:45 UTC, pjuza commented on components/src/test/java/org/openhubframework/openhub/component/ComponentTestConfig.java
> +@PropertySource(value = {"classpath:/config/application-test-default.properties"})
application-test-default.properties doesn' have anything with "test" profile. I used this name to describe that the file contains default values for tests ...

2017-01-23 16:46 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    /**
OK, I will do it.

2017-01-23 16:46 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +     * FailedCount of partly fails before message will be marked as completely FAILED.
Corrected

2017-01-23 16:47 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +
I was intention firstly but then I forgot about it :)

2017-01-23 16:53 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/AsynchConstants.java
> +            + "?concurrentConsumers={{" + ASYNCH_CONCURRENT_CONSUMERS + "}}&waitForTaskToComplete=Never"
I only introduced constants for parameters without tryping to modify it. And when I introduced @ConfigurableValue then I haven't changed use of parameters in the code too => it's for another task.
I would mention my text from wiki:

> If you need to have one place for adding/administrating a configuration parameter common for all cluster nodes then database has to be used. Furthermore you can change parameter values on the fly (if implementation that use specific parameter can get current value anytime the parameter is used).

2017-01-23 16:54 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/alerts/AlertsPropertiesConfiguration.java
> +        for (String propName : Tools.getAllKnownPropertyNames((ConfigurableEnvironment)env)) {
You are right, same with ThrottlingPropertiesConfiguration

2017-01-23 16:55 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/directcall/DirectCallHttpImpl.java
>                      if (status >= 200 && status < 300) {
OK, I will use it ...

2017-01-23 17:01 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/confcheck/ConfigurationChecker.java
> +     * Checks if configuration parameter "ohf.server.localhostUri" is valid - calls PING service.
Each node will have its own URI (more nodes can have identical localhost URIs) - these URIs are used by nodes themselves, not for calls via load balancer

2017-01-23 19:37 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/configuration/FileExternalPropertiesAutoConfiguration.java
> +public class FileExternalPropertiesAutoConfiguration
I create task https://openhubframework.atlassian.net/browse/OHFJIRA-39 for solving it in the future.
There are another possibilities how to do it at this moment, it's not critical to solve it here (it's question if it is possible):

> Command line arguments.
Properties from SPRING_APPLICATION_JSON (inline JSON embedded in an environment variable or system property)
ServletConfig init parameters.
ServletContext init parameters.
JNDI attributes from java:comp/env.

2017-01-23 20:01 UTC, pjuza commented
I went through all comments and commited few changes. Please review again ...

2017-01-24 10:04 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/AsynchConstants.java
> +            + "?concurrentConsumers={{" + ASYNCH_CONCURRENT_CONSUMERS + "}}&waitForTaskToComplete=Never"
Ok it makes sense

2017-01-24 10:05 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/confcheck/ConfigurationChecker.java
> +     * Checks if configuration parameter "ohf.server.localhostUri" is valid - calls PING service.
I know and therefore I am talking about if this property name reflects usage.

2017-01-24 10:06 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/configuration/FileExternalPropertiesAutoConfiguration.java
> +public class FileExternalPropertiesAutoConfiguration
Yes, I agree. It is not critical, only my hint.

2017-01-24 10:08 UTC, hanusto approved these changes

2017-01-24 10:16 UTC, hanusto commented
Only one point: `ohf.server.localhostUri` is property to hold URI of OHF instance (node). We have task [OHFJIRA-30](https://openhubframework.atlassian.net/browse/OHFJIRA-30) to hold details about each node in DB. In property file (not shared across all nodes) there will be property to hold unique identifier of node which will represent a bind bridge to data in DB.

2017-01-24 11:51 UTC, merged