Feature/ohfjira 30 nodes evidence
OpenWiseSolutions/openhub-framework pull request #28
Opened 2017-02-08 16:51 UTC by openhubframework

2017-02-10 15:29 UTC, pjuza commented
Firstly add description to this PR to describe what you are solving and how it is solved.

2017-02-10 17:19 UTC, pjuza requested changes
Main points from my perspective:
- encapsulate as much as possible logic into Node object (I know that Message is not the right example but we need to refactor it in the meantime.
- use ConfCheck

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
>              .append("processingPriority", processingPriority)
Is correct to have guaranteedOrder / excludeFailedState / processingPriority in equals method?

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +public class Node implements HumanReadable {
Wouldn't be better to use "cluster_node" instead of node. When somebody says node then I imagine XML node firstly ...

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +                .append("description", description)
Use trim() because description can have over 2000 characters ...

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +    public void setCode(String code) {
Is it ok that code/name can be set when Node is created? When node is created why somebody want's to change code or name?
Hibernate (JPA) doesn't need to have public set* methods.

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +    public void setState(NodeState state) {
I would prefer to have as much business logic as possible in true objects, not in services. Avoid to anemic domain model (https://en.wikipedia.org/wiki/Anemic_domain_model).

I suggest the following:
- replace setState with methods such as run(), stop(), ...
- add business logic checks if transfers between different states are possible

2017-02-10 17:19 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +}
Please add toString()

2017-02-10 17:19 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/NodeService.java
> +    void insertNode(Node node);
I know it's not for thisissue but I would like to change like in WisePorter - to have true objects which will be able to saves into DB themselves. Not to have services with methods which manipulate with object's state.

2017-02-10 17:19 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/NodeService.java
> +    void setStoppedStateOnActualNode();
You should move all these methods to Node object, wouldn't it be better?
If it's here because of transaction demarcation then we should consider using AOP (https://openhubframework.atlassian.net/browse/OHFJIRA-32)

2017-02-10 17:19 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/NodeService.java
> +    Long getActualNodeId();
Why getActualNodeId when you have getActualNode ?

2017-02-10 17:19 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +    @Value("${node.actualInstance.code}")
Use constant for property name + add prefix org.openhubframework.openhub.common.OpenHubPropertyConstants#PREFIX

2017-02-10 17:19 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        return nodeDao.getAllNodes();
I would use Collections.unmodified ...

2017-02-10 17:19 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        return getActualNode().getState().equals(NodeState.STOPPED);
I prefer to move all these methods to Node object, encapsulate logic around node's state

2017-02-10 17:19 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        if (StringUtils.isBlank(actualNodeCode)) {
Please implement org.openhubframework.openhub.core.confcheck.ConfCheck contract
See org.openhubframework.openhub.core.confcheck.ConfigurationChecker

2017-02-10 17:19 UTC, pjuza commented on core/src/main/resources/db/db_schema_postgreSql_2_0.sql
> +    state           varchar(64)     not null,
Isn't it too much for enum item?

2017-02-10 19:26 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +}
Why toString() method in ENUM?

2017-02-10 19:29 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        return nodeDao.getAllNodes();
In here it does not make sense. This is service and add/remove operation on list don't change data in database.

2017-02-10 19:35 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +    public void setCode(String code) {
For me it is important have possibility change name and code. When i create node with bad code or name (typing error) my only posibility would be delete node and create new one. This is not user friendly.

2017-02-10 20:03 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +                .append("description", description)
You mean substring? Trim not help with too long string.

2017-02-10 20:47 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +    public void setCode(String code) {
I agree with this possibility from user's point of view but even then object can be immutable ...

2017-02-10 20:47 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +                .append("description", description)
Yes, substring ...

2017-02-24 09:07 UTC, pjuza reviewed
I see lot of good changes in the right way but there are still several points from review for discussion.
Please go through all comments and write me your feedback.

2017-02-24 09:07 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +}
You can use toString() in Enum if you have more attributes ...

2017-02-24 09:07 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/PartlyFailedMessagesPoolRoute.java
> +    public boolean isProcessExistingMessage() {
Better name should be isProcessingExistingMessage

2017-02-24 09:07 UTC, pjuza commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/StopController.java
> +    private boolean isNodesInStopping() {
Wouldn't be isNodeInStopping() better name?

2017-02-24 09:07 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        return nodeDao.getAllNodes();
I agree ...

2017-02-24 09:07 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +public class NodeServiceImpl implements NodeService, ConfCheck {
I would prefer to have all this implementation directly in Node object but I agree that we should add AOP support (https://openhubframework.atlassian.net/browse/OHFJIRA-32).

2017-02-24 09:07 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDao.java
> +    Node getNodeById(Long nodeId);
Do you really need this method?
I see you have nodeId (long) in Message object => wouldn't be better to change it to object approach = Message.getNode istead of Message.getNodeId ?

2017-02-24 20:09 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDao.java
> +    Node getNodeById(Long nodeId);
This method is prepared for view/edit in web client (like delete method, or getAllNodes() - we don't need them yet).
In message i will add node property with set/get methods.

2017-02-24 20:10 UTC, openhubframework commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/StopController.java
> +    private boolean isNodesInStopping() {
It would be better. I will rename it.

2017-02-24 20:10 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/PartlyFailedMessagesPoolRoute.java
> +    public boolean isProcessExistingMessage() {
It would be better. I will rename it.

2017-02-24 20:12 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +public class NodeServiceImpl implements NodeService, ConfCheck {
After we will have AOP support in project i will move these method into Node class.

2017-02-24 20:25 UTC, openhubframework commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/StopController.java
> +    private boolean isNodesInStopping() {
This method checks all nodes state and return if all nodes is in stopping. I will rename it to isAllNodesInStopping - this would be better

2017-02-26 16:01 UTC, openhubframework commented
Changes are ready to review.

2017-02-26 17:36 UTC, pjuza commented
It looks fine but I have last three questions please:
- isn't ClusterNode better than Node? :)
- why is varchar(64) for code in node table? I remember that it's better to have small fixed character size for types which would be used for often searching (it's better for indexing). Maybe I'm wrong ...
- wouldn't be better to have immutable Node object? Instead of setCode() method create new object ...

2017-02-26 20:13 UTC, hanusto requested changes
I did review. Concept of solution for node evidence is ok. We should discuss or changed something according to proposal. After that everything needed should be documented. The most important is PR description with link reference to JIRA issue (see for example https://github.com/OpenWiseSolutions/openhub-framework/pull/27). There are also many recommendation for renaming, for example `process` to `handle`. Thanks for your clarification.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String NODE_ACTUAL_INSTANCE_CODE = PREFIX + "node.actualInstance.code";
In logging improvement we added `ohf.cluster.nodeid` property as identifier of node in clustered environment. We should consolidate that. This property is used in `ohf-logback.xml` file.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
> +    public Node getNode() {
Why `getNode()` *and also* `getNodeId()`? It is similar getter (node.id), i prefer first one.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
>              .append("processingPriority", processingPriority)
This is not change of this PR, but I think no. We should use only PK or natural mandatory identifiers.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +public class Node implements HumanReadable {
I agree with Petr.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +public class Node implements HumanReadable {
I suggest to rename all status-based methods, for example `setRunState`. From `run` (or `process`) method I expect sophisticated behaviour than only change of state.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +    public void setCode(String code) {
I imagine some codes (and names) but I think that in most cases it should be node1, node2 or something similar. I don`t think that this attribute is important from user point of view...

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +     * Node process new and existing (saved messages in ESB) messages.
Cluster node `process`, or better verb is `handles`.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +     * Node process only existing messages. New messages/requests are rejected.
handles...

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +     * Node not process existing messages and new messages.
handles...

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Node.java
> +public class Node implements HumanReadable {
I also recommend to rename `process` to `handle`.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +     * @param processNewMessages      @code true} node process new incoming messages, {@code false} - otherwise
probably lost `{`

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +        return new ToStringBuilder(this)
`return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE)`

2017-02-26 20:13 UTC, hanusto commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/NodeService.java
> +    void insertNode(Node node);
We can use only `insert` method, without node, it is domain of service. This method should returns inserted `Node` entity for example where node id is generated. It is the same of update method. It is good approach and design pattern to return updated object.

2017-02-26 20:13 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/NodeState.java
> +    public boolean isProcessNewMessages() {
for all getters = Gets `true` if . And maybe better name is: `isAbleToProcessNewMessages` or something similar. The same for method below...

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/AsynchMessageRoute.java
> +     * @throws StoppingException if node not proess existing message
typo `proess`, therefore I recommend to use `handle` verbs :)

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDaoJpaImpl.java
> +    @Transactional(propagation = Propagation.MANDATORY)
Is this necessary? Service layer is marked as transaction, so it is ok. Additional mandatory propagation decreases performance.

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +    private String actualNodeCode;
Why `ConfigurationItem` approach is not used?

```
@ConfigurableValue(key = CoreProps.NODE_ACTUAL_INSTANCE_CODE)
private ConfigurationItem<String> actualNodeCode;
```

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +     * Contains actual node for this instance application server.
I would remove `application server`. OpenHub can runs as simple microservice without application server.

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +@Service
`@Transactional(readOnly = true)`

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        if (node.getNodeId().equals(getActualNode().getNodeId())) {
Why node#equals is not used?

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        return nodeDao.getAllNodes();
But **unmodified** design is good approach for caller. From caller point of view we dont know implementation detail.

2017-02-26 20:13 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        //test if configuration value exist
We should perform double check: if `getActualNode()` returns node (instead of `null`), we can skip next processing. This section is synchronized, it is ok, but we can have situation when two one thread is suspended and waits for unlock previously acquired thread.

2017-02-27 17:06 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
> +    public Node getNode() {
There is getNodeId because method getNode() gets data from database. When someone needs only node identifier then call method getNodeId - without load data from database.

2017-02-27 17:55 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        //test if configuration value exist
This control in getAcutalNode is only for tests, because in tests method check() is not called. In production environment actualNode attribute never be null.

2017-02-27 18:02 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String NODE_ACTUAL_INSTANCE_CODE = PREFIX + "node.actualInstance.code";
I will set in ohf-logback.xml node property on ohf.node.actualInstance.code

2017-02-27 18:07 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDaoJpaImpl.java
> +    @Transactional(propagation = Propagation.MANDATORY)
Is really performance decreases so big? I am calmer if in dao insert/update/delete methods is transaction exist control.

2017-02-28 06:58 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDaoJpaImpl.java
> +    @Transactional(propagation = Propagation.MANDATORY)
For big load yes. There must be additional extra check for transaction...

2017-02-28 07:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/node/NodeServiceImpl.java
> +        //test if configuration value exist
Sorry I don't understand that

2017-02-28 07:04 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
> +            .append("nodeId", nodeId)
getNodeId() is safer because there is many-to-one relation with lazy type so node is proxied -> we should ever call methods instead fields.

2017-02-28 07:08 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/Message.java
> +    public Node getNode() {
Ok, I understand this optimalization but you should documented it why this approach is used.

2017-03-14 21:23 UTC, pjuza requested changes
I like these changes with immutable vs mutable node. 
I would think about if common abstract node class isn't cleaner solution, also with using in DAO layer.

2017-03-14 21:23 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/ChangeNode.java
> +public interface ChangeNode {
What about ChangeNodeCallback or ChangeNodeSetter (inspiration by JdbcOperations from Spring)

2017-03-14 21:23 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/dao/NodeDao.java
> +    void insert(MutableNode node);
Why don't use Node interface only?

2017-03-14 21:23 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/node/ImmutableNode.java
> +    public boolean isStopped() {
I would create AbstractNode with common functions (e.g. state functions) for ImmutableNode and MutableNode ...
Maybe you could add all attributes (= JPA mappings) to this abstract class and use this abstract class in DAO layer.

2017-03-14 21:23 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/MutableNode.java
> +    public void setRunState() {
Why these state() methods aren't in interface Node (or create new interface NodeLifecycle with these state methods only). 
I miss validations if it's possible to set specific state when node is in another state.
If there is flow of node's state then I would better describe it.

2017-03-19 16:28 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/entity/MutableNode.java
> +    public void setRunState() {
Because Node interface is only for reading. Node interface can not have setter, bacause it is immutable.
Validations it is not needed. There is no flow, you can change node state from any into any state.

2017-03-19 16:29 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/node/ImmutableNode.java
> +    public boolean isStopped() {
AbstractNode can not have attributes, because in immutable node is all attributes final. AbstractNode is good idea, i will create it.

2017-03-19 16:34 UTC, openhubframework commented on core-spi/src/main/java/org/openhubframework/openhub/spi/node/ChangeNode.java
> +public interface ChangeNode {
You have right ChangeNodeCallback will be better. I will rename it

2017-03-19 17:43 UTC, openhubframework commented
It is prepare for review:

- I created new class AbstractNode
- In NodeDao interface is now work only with Node interface

2017-03-19 17:57 UTC, pjuza commented
You wrote "AbstractNode can not have attributes, because in immutable node is all attributes final." -  I don't think so because you don't have to have final modifier, you can use suitable constructor and no setter methods.

2017-03-19 17:58 UTC, pjuza approved these changes
Good job, I approve it ...

2017-03-19 18:43 UTC, openhubframework commented
"I don't think so because you don't have to have final modifier, you can use suitable constructor and no setter methods." - This is true, but if you dont have final modifier, you can change attribute values with reflection.

2017-04-04 20:05 UTC, hanusto approved these changes

2017-04-05 05:46 UTC, hanusto commented
We will have to update documentation. For now, I merged that.

2017-04-05 05:46 UTC, merged