OHFJIRA-27 - Add support for clustered jobs (quartz)
OpenWiseSolutions/openhub-framework pull request #33
Opened 2017-03-12 19:01 UTC by openhubframework

2017-03-14 22:38 UTC, pjuza requested changes
Quite big implementation :).

I don't have any critical comments, only many smallers. I'm not able to validate the whole model (because it's too big ...) but I believe it's ok ...

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/ClusterExecuteType.java
> +public enum ClusterExecuteType {
Wouldn't be better ScheduledJobType?

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzSimpleTrigger.java
> + * Defined one {@link SimpleTrigger} in {@link QuartzJob}.
Better describe why use this annotation instead of QuartzCronTrigger

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/SimpleTriggerMisfireInstruction.java
> +     * @see SimpleTrigger
Isn't it needless to add more times "@see SimpleTrigger"?

2017-03-14 22:38 UTC, pjuza commented on core-spi/src/main/java/org/openhubframework/openhub/spi/quartz/TriggerFactory.java
> + * Every trigger instance running concurrent in all nodes in cluster at the same time
language mistake - Every trigger instance is able to running in ...

Factory for create new => Factory class for creating new ...

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzSimpleTrigger.java
> +    ClusterExecuteType clusterExecuteType();
Why is there not default value? I would expect concurrent ...

2017-03-14 22:38 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/PartlyFailedMessagesJob.java
> + * @author Petr Juza
I don't know why there are so many @see items in specific implementations, I would remove them.

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> +    QuartzCronTrigger[] cronTriggers() default {};
Is it possible to set cron and simple triggers at the same time?
If not then add description to JavaDoc + it's possible to define common parent class/annotation and then have only one trigger parameter?

2017-03-14 22:38 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/quartz/OpenHubQuartzJob.java
> + * For base use see in {@link {@link QuartzJob}}.
Remove once @link ...

2017-03-14 22:38 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> +    String name() default StringUtils.EMPTY;
I see method in QuartzUtils for generating job's name. Wouldn't be better to define JobNameGenerator interface with default implementation from QuartzUtils?

2017-03-14 22:38 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/config/QuartzConfig.java
> +    public Properties quartzPostgresProperties() {
I would define it in property file because when you add new DB then you should always add new method to the code.

2017-03-19 19:04 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> +    QuartzCronTrigger[] cronTriggers() default {};
Yes it is. One job can have one or more QuartzCronTrigger and one or more QuartzSimpleTrigger at the same time.

2017-03-19 19:06 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> +    String name() default StringUtils.EMPTY;
In QuartzUtils is not method for generate job name, but for generate trigger name. Job name is defined in annotation attribute name. I will create TriggerNameGenerator interface.

2017-03-19 19:07 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/queue/PartlyFailedMessagesJob.java
> + * @author Petr Juza
I will remove it

2017-03-19 19:07 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/SimpleTriggerMisfireInstruction.java
> +     * @see SimpleTrigger
I will remove it and add "@see SimpleTrigger" on class.

2017-03-19 19:11 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/ClusterExecuteType.java
> +public enum ClusterExecuteType {
I dont know. This is not for job, but it is for trigger. And maybe this is not good. I will add this setting into job. And name can be JobExecuteTypeInCluster.

2017-03-19 19:19 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzSimpleTrigger.java
> +    ClusterExecuteType clusterExecuteType();
I think that default value is not good idea. Set this attribute is important and when he has default value, many user not fill them.

2017-03-20 05:59 UTC, pjuza reviewed
I went through all your comments and it's OK for me.

Only one thing - how to solve when new database type will be used? At this moment you should add new code and it's not flexible ...

2017-03-20 18:06 UTC, openhubframework commented
You have right, this is not good solutions. I will change it and move properties into configuration file application-h2.cfg or application-postgres.cfg.

2017-03-25 20:50 UTC, openhubframework commented
It is ready for review.

Changes:

- Move quartz settgins from QuartzConfig into application properties

- Add name() and group() into QuartzSimpleTrigger and QuartzCronTrigger - now user can direct specify trigger name and trigger group (generator is not necessary)
- Edit javadoc (remove @see etc.)

2017-03-27 22:16 UTC, pjuza reviewed
Two common points:
- test coverage descreased about 6% - it's too much, please add more unit tests
- please add wiki pages with information about using your quartz API. It will be helpful to better understand your code

2017-03-27 22:16 UTC, pjuza commented on common/src/main/java/org/openhubframework/openhub/common/Tools.java
> +    public static Properties getPropertiesWithPrefix(ConfigurableEnvironment env, String propertyNamePrefix) {
Consider to use Tools.getAllKnownPropertyNames in implementation ...

2017-03-27 22:25 UTC, pjuza reviewed
Once again review ...

2017-03-27 22:25 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> + * </p>
if you have starting and ending element p then it will create two empty lines and you propably want to have one line, don't you?

2017-03-27 22:25 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> + * Every job must have at least one {@link QuartzCronTrigger} or {@link QuartzSimpleTrigger}. And one job can have
it's quite complicated sentence :)

2017-03-27 22:25 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/quartz/jobfactory/BeanMethodJobFactory.java
> +    public void setApplicationContext(final ApplicationContext applicationContext) {
We have already full AOP support thus you can use @Configured ...

2017-03-29 18:01 UTC, openhubframework commented on common/src/main/java/org/openhubframework/openhub/common/Tools.java
> +    public static Properties getPropertiesWithPrefix(ConfigurableEnvironment env, String propertyNamePrefix) {
I will use it. One small disadvantage is, that list will be use twice (first for getting names and second for getting values for names).

2017-03-29 18:04 UTC, openhubframework commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> + * </p>
I dont understand. Where is two empty lines? In HTML or in source code?

2017-03-29 18:58 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/common/quartz/QuartzJob.java
> + * </p>
When you use ending p and starting p ...

2017-04-02 17:55 UTC, openhubframework commented on core/src/main/java/org/openhubframework/openhub/core/common/quartz/jobfactory/BeanMethodJobFactory.java
> +    public void setApplicationContext(final ApplicationContext applicationContext) {
I used Autowired for load ApplicationContext property

2017-05-03 19:36 UTC, hanusto approved these changes
For this moment these PR meets the requirements.

2017-05-03 19:41 UTC, merged