OHFJIRA-52 list of exposed webservices
OpenWiseSolutions/openhub-framework pull request #52
Opened 2017-05-13 23:42 UTC by kkovarik

### ABOUT 
Overview of exposed Webservices. See related JIRA task for more info: https://openhubframework.atlassian.net/browse/OHFJIRA-52

### CHANGES
* added new REST endpoint GET /api/ws with simple test. It does reuse WsdlRegistry functionality.

2017-05-14 12:53 UTC, pjuza requested changes
Is there API documentation in Apiary? Also mockup diagram for GUI developers in Balsamiq would be nice.

2017-05-14 12:53 UTC, pjuza commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +public class WsController extends AbstractOhfController {
Maybe WsdlController would be better ...

2017-05-14 12:53 UTC, pjuza commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rpc/WsInfoRpc.java
> +public class WsInfoRpc {
Same as controller - wouldn't be better to use "wsdl" prefix, isn't it more descriptive?

2017-05-14 17:16 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +public class WsController extends AbstractOhfController {
And where to expose it, directly under /api/wsdl?

No problem with that, I do not have any strict opinion on this, my initial thinking was like - ok, what is wsdl? definition of service, resource itself desired by consumer is the webservice.

2017-05-14 17:25 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rpc/WsInfoRpc.java
> +public class WsInfoRpc {
Possibly, as in previous comment, if it is the wsdl resource this endpoint should list, then yes, I will change it...

2017-05-14 17:27 UTC, kkovarik commented
I apologize, the links to drafts of mockup and API documentation were mentioned only in the JIRA task:

Api draft: http://docs.openhubframework.apiary.io/#reference/0/openhub-web-services/gets-list-of-exposed-webservices
Mockup draft: https://openwise.mybalsamiq.com/projects/openhub/WS%20overview

2017-05-14 18:13 UTC, pjuza commented
Please change URI: /api/ws -> /web/admin/api/ws

If you accept change from ws to wsdl then please change also names in API.

2017-05-14 18:14 UTC, pjuza commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rpc/WsInfoRpc.java
> +public class WsInfoRpc {
Yes, it's overview of input web service definitions (wsdl).
We will add overview of REST services in the next version ...

2017-05-14 18:54 UTC, hanusto requested changes
I recommend to rename WS -> WSDL and whole endpoint should be in /api/services context. After that I agree with that.

2017-05-14 18:54 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +    public static final String REST_URI = BASE_PATH + "/ws";
And WSDL for endpoint URL too. Maybe my recommendation is `/api/services/wsdl`

2017-05-14 18:54 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +    private static final String WS_URI = "/ws/";
I dont know if the WS context can be configured or not. If yes, this should be the same.

2017-05-14 18:54 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +    @GetMapping(produces = {"application/xml", "application/json"})
great

2017-05-14 21:55 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +    private static final String WS_URI = "/ws/";
Cannot, however changed it to the constant used to actually configure the context (RouteConstants.WS_URI_PREFIX).

2017-05-14 21:55 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/ws/rest/WsController.java
> +    public static final String REST_URI = BASE_PATH + "/ws";
Done.

2017-05-14 22:03 UTC, kkovarik commented
Thanks for the review, updated endpoint to **/api/services/wsd**l and refactored to WsdlController & WsdlInfoRpc etc. feel free to check again.

API documentation updated: http://docs.openhubframework.apiary.io/#reference/0/openhub-web-services, now I am using collection wrapping as it is introduced in PR#53: https://github.com/OpenWiseSolutions/openhub-framework/pull/53

Will wait until PR#53 is merged, then rebase this branch to use the common CollectionWrapper as well...

2017-05-15 05:05 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/services/wsdl/rest/WsdlController.java
> +     * @return list of WsInfoRpc domain objects wrapped in CollectionWrapper.
WsInfoRpc -> WsdlInfoRpc, or use {@link WsInfoRpc}. This was refactored automatically. The same for {@link CollectionWrapper}.

2017-05-15 05:06 UTC, hanusto approved these changes
Now it is perfect. Only one improvement introduced -> javadoc. PR https://github.com/OpenWiseSolutions/openhub-framework/pull/53 merged so you can rebase it with requested changes.

2017-05-15 07:20 UTC, pjuza approved these changes

2017-05-15 18:46 UTC, hanusto commented
PR #53 is merged, so you can rebase that.

2017-05-15 18:55 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/services/wsdl/rest/WsdlController.java
> +     * @return list of WsInfoRpc domain objects wrapped in CollectionWrapper.
Thanks, missed that, fixed.

2017-05-15 19:14 UTC, kkovarik commented
@hanusto thanks for fast merge, rebased on current develop.

2017-05-15 19:19 UTC, merged