OHFJIRA-70 : old gui cleanup
OpenWiseSolutions/openhub-framework pull request #66
Opened 2017-08-01 06:09 UTC by kkovarik

Old GUI in web-admin module removal

#### CHANGES
* removed old gui resources (css, ftl templates etc...), controllers and configuration
* configured spring-security to work with new admin-console properly: removed all 3xx redirects, if not logged, unauthorized 401 is returned, if login fails then 403
* changed configuration of basic authentication for webservices, as it has not correctly worked in standalone mode (see comment in WebSecurityConfig)
* switched location of spring-boot maven plugin, -exec repackaged archive is now only in web-admin submodule

#### RELATED JIRA
* https://openhubframework.atlassian.net/browse/OHFJIRA-70

2017-08-01 06:20 UTC, pjuza approved these changes
Big step to finish 2.x version. Thanks.

2017-08-01 06:20 UTC, pjuza commented on web-admin/src/main/java/org/openhubframework/openhub/web/common/WebProps.java
> +    public static final String SESSION_CONCURRENCY_LIMIT = OpenHubPropertyConstants.PREFIX + "admin.console.session-concurrency.limit";
I added on wiki (https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/33599/OpenHub+configuration)

2017-08-01 11:06 UTC, hanusto commented
The fastest way how to increase code coverage - remove unused code lines :)

2017-08-01 11:24 UTC, hanusto requested changes
Please try to remove log packages and unused classes.

2017-08-01 11:24 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/log/LogController.java
> -import org.openhubframework.openhub.admin.services.log.LogParser;
Please remove LogParser class, or maybe whole package _org.openhubframework.openhub.admin.services.log_

2017-08-01 11:24 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/log/LogController.java
> -import org.openhubframework.openhub.admin.services.log.LogParser;
And message report service

2017-08-01 11:24 UTC, hanusto commented on web-admin/src/main/java/org/openhubframework/openhub/admin/config/AdminSecurityConfig.java
> +                        .antMatchers(WEB_URI_PREFIX + "console/**")
Maybe we can reuse `spring.mvc.static-path-pattern` property.

2017-08-02 19:40 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/web/log/LogController.java
> -import org.openhubframework.openhub.admin.services.log.LogParser;
Removed, entire package & messageReportService as well.

2017-08-02 19:43 UTC, kkovarik commented on web-admin/src/main/java/org/openhubframework/openhub/admin/config/AdminSecurityConfig.java
> +                        .antMatchers(WEB_URI_PREFIX + "console/**")
Don´t know, the WEB_URI_PREFIX has trailing slash /, and property now starts with slash as well... /console/**...

2017-08-03 08:12 UTC, hanusto approved these changes

2017-08-03 08:12 UTC, merged