Config params : improved data types formating
OpenWiseSolutions/openhub-framework pull request #69
Opened 2017-08-29 16:26 UTC by kkovarik

### ISSUE
* db params are stored in db as Strings, on RPC the same, therefore when jackson marshalled them they were always with quotes - "true", "42"

### CHANGES
* in DbConfigurationParamRpc, currentValue & defaultValue of param is now java.lang.Object. When DB entity is converted, there is extra manual serialization & deserialization from db entity String.
* DataTypeEnum was extended for each type it now has defined two Functions. one for serialization (Object -> String) other one inverse (String -> Object).
* for example, integer parameter: in DB it is stored still as string, when DB entity is converted to DbConfigurationParamRpc, function Integer.parse() defined in DataTypeEnum is applied

2017-08-30 11:33 UTC, pjuza requested changes
I don't know exactly how to solve it but we have duplicity at this moment.

Maybe question is if this conversion should be in core module (now DataTypeEnum) and not in web module because it's specific for REST services ...

2017-08-30 11:33 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/DataTypeEnum.java
> +    STRING(String.class, stringDeserialization(), stringSerialization()),
Nice solution via JDK8 functions but please two things for considaration:
- there is org.openhubframework.openhub.common.converter.TypeConverterEnum - use this class or/and replace implementation by your implementation? Your implementation is identical to TypeConverterEnum besides from FILE and PATTERN
- why don't use converters in Spring (org.springframework.core.convert.ConversionService), why implement something by ourselves?

2017-08-31 19:48 UTC, kkovarik commented
Update: now conversion is done directly on db entity - getCurrentValueRaw & getDefaultValueRaw methods added...

2017-08-31 19:51 UTC, kkovarik commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/DataTypeEnum.java
> +    STRING(String.class, stringDeserialization(), stringSerialization()),
Well, tried solution with ConversionService, however does not seem nice solution without bigger refactoring, as conversion is done on db entity (or rpc). So I would have to pass the conversion service bean somehow. Via getters or setters or other methods.

So now I went for the TypeConverterEnum as simple solution, please check what it looks like now.

2017-09-01 08:12 UTC, pjuza approved these changes
Nice solution ...

2017-09-01 08:12 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/DbConfigurationParam.java
> +    public Object getCurrentValueRaw() {
I don't know if "raw" value is the best name. What about getCurrentValueAsObject or change original method getCurrentValue->getCurrentValueAsString and use getCurrentValue for this.

2017-09-01 08:12 UTC, pjuza commented on web-admin/src/test/java/org/openhubframework/openhub/admin/web/configuration/rest/DbConfigurationControllerTest.java
> +                .add("defaultValue", 10)
Unit test for boolean would be great.

2017-09-01 08:36 UTC, hanusto requested changes
Please rename methods and add test to verify correct behaviour for boolean based types.

2017-09-01 08:36 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/DbConfigurationParam.java
> +    public void setDefaultValueRaw(Object defaultValue) {
Change the name of setter as well.

2017-09-01 08:36 UTC, hanusto commented on web-admin/src/test/java/org/openhubframework/openhub/admin/web/configuration/rest/DbConfigurationControllerTest.java
> +                .add("defaultValue", 10)
I agree

2017-09-01 14:34 UTC, kkovarik commented on web-admin/src/test/java/org/openhubframework/openhub/admin/web/configuration/rest/DbConfigurationControllerTest.java
> +                .add("defaultValue", 10)
Added unit test for get & update of boolean attributes, good idea 👍

2017-09-01 14:35 UTC, kkovarik commented
Renamed getters & setters, thanks for feedback!

2017-09-02 10:56 UTC, hanusto approved these changes
Thanks for PR.

2017-09-02 10:56 UTC, merged