[OHFJIRA-6] : messages in final state
OpenWiseSolutions/openhub-framework pull request #94
Opened 2018-11-09 15:51 UTC by kkovarik

## Final messages handling
**Motivation**: to have mechanism how to handle old messages in final state, that would otherwise be in datastore forever.

**Implemented solution**: job is deleting messages after some preconfigured time has elapsed from their last update time.

### Implementation
tried to keep it reasonably simple, yet customizable

#### Core components:
##### FinalMessagesProcessingJob
* job, configured to be executed only on one node of cluster
* does call FinalMessagesProcessingService
##### FinalMessagesProcessingService
* finds messages in db that are eligible for "processing" (aka delete)
* provided implementation does use configuration properties for each state
* states are hardcoded in current implementation, there is check that all parameters are configured
* does call FinalMessageProcessor on each message, catches exceptions so that failure to delete one message should not affect the others

##### DeleteFinalMessageProcessor implements FinalMessageProcessor
* default implementation
* does delete provided message with the related entities - extcalls & requests & responses.
* before delete all the registered DeleteFinalMessageListener beans are invoked, in order. It is not wrapped in try catch block, if listener throws exception, message will not be deleted.
* delete is performed in standalone transaction and commited afterwards.
 
##### DeleteFinalMessageListener
* just interface, no implementation is provided in core
* ideally this should be the only place to implement project specific, there will be some archiving or reporting or logging etc. done, after which, the message can be safely deleted

#### Notes
* had to add some delete methods to Dao´s, did not added them to Service layer, as they are only called from DeleteMessageProcessor
* job and all the beans are conditionaly registered by using property `ohf.asynch.finalMessages.processingEnabled`, by default disabled
* minor backward compatible change in MessageFilter, to enable search for messages by state & lastUpdate only, not to have to add receivedFrom

### Configuration
```
# final messages processing enabled or disabled. Note: cannot be defined in database, 
# needs to be in properties.
ohf.asynch.finalMessages.processingEnabled = true/false

# final messages processing job interval, in seconds.
ohf.asynch.finalMessages.processingIntervalSec=

# maximum number of messages processed per job.
ohf.asynch.finalMessages.iterationMessageLimit=10000

# duration in seconds to keep messages in OK state in the datastore. After this period expires and
# there is no other action with the message, it will be processed as final (deleted probably)
ohf.asynch.finalMessages.ok.saveTimeInSec=0

# duration in seconds to keep messages in CANCEL state in the datastore.
ohf.asynch.finalMessages.cancel.saveTimeInSec=28800

# duration in seconds to keep messages in FAILED state in the datastore.
ohf.asynch.finalMessages.failed.saveTimeInSec=14400
```
### Possible pittfals 
* performance - how many messages should be processed in single iteration? when enabled on already full database? now there is configurable limit. however it is fetched by single query, could make sense to make multiple queries if this parameter should be too big...

2018-11-11 22:22 UTC, pjuza requested changes

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +/*
add package-info.java files into packages ...

2018-11-11 22:22 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC = PREFIX + "asynch.finalMessages.ok.saveTimeInSec";
What does it mean if value is 0? Please describe it.
Maybe this comment is mainly for description on wiki to be clear what does it mean to use 0 value for time intervals.

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +        FINAL_MSG_STATES_CONFIG.put(MsgStateEnum.OK, CoreProps.ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC);
It would be nice to have definition of final states at one place only. See org.openhubframework.openhub.api.entity.MsgStateEnum#isFinal

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +    protected ConfigurationItem<Long> messagesTechnicalLimit;
I like using limit, good idea

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +        // so if listener fails, it will effectivelly cancel the delete
Mispelling - effectively

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
I had different idea how to implemented it - I wanted to define interface, similar to FinalMessageProcessor in your implementation. And this interface will have default implementation that deletes records from data store. And if you would like to change it for your project then you will implement it in your way. 
But your implementation deletes records in every case, only custom implementations before deletion itself are possible.

2018-11-11 22:22 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
I would add final modifier to this method - this method represents "core" of this class and should be unchangeble. You can override each delete method but core logic should be always same.

2018-11-12 08:01 UTC, hanusto requested changes

2018-11-12 08:01 UTC, hanusto commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/finalmessage/FinalMessageProcessor.java
> + * to be processed by this processor. After this, they should not be in OpenHub datastore
According to comment from @pjuza it is wrong javadoc. _FinalMessageProcess_ is only about processing messages in final state. Removing or archiving is one of many action what can be done.

2018-11-12 08:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    protected List<DeleteFinalMessageListener> getSortedListenerList() {
Why? If each component has Order annotation, it is sorted by default.

2018-11-12 08:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public DeleteFinalMessageProcessor(PlatformTransactionManager transactionManager) {
Which _ PlatformTransactionManager_? OpenHub?

2018-11-12 08:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +public class DeleteFinalMessageProcessor implements FinalMessageProcessor {
It is not spring component?

2018-11-12 08:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
But we have to force to delete outdated messages. If this listener will be Spring component, it will be possible by Primary annotation but it should be exceptionally.

2018-11-12 08:01 UTC, hanusto commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    protected List<DeleteFinalMessageListener> getSortedListenerList() {
I see, this is safer. I agree.

2018-11-12 08:01 UTC, hanusto commented on core/src/main/resources/db/migration/postgresql/V1_0_3__final_messages.sql
> +-- final messages processing enabled or disabled.
In future we should migrate from Flyway to Liquibase...

2018-11-12 08:01 UTC, hanusto commented on core/src/test/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImplTest.java
> +import org.openhubframework.openhub.api.asynch.finalmessage.FinalMessageProcessor;
In future we can reorder imports = it will be necessary to improve our code style.

2018-11-12 09:44 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +        FINAL_MSG_STATES_CONFIG.put(MsgStateEnum.OK, CoreProps.ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC);
Ok, if you think it will ever by changed It´s small change as I was anticipating it :) 

I have to relative the relationship between State + Prop, so I will have to make dynamic resolving like:
`asynch.finalMessages.<lowercased-name-of-state>.saveTimeInSec`, ok?

What should happen if configuration value is not found, exception during startup? Other solution would be default value, but I´m not too fond of it.

2018-11-12 09:44 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +        // so if listener fails, it will effectivelly cancel the delete
Fixed, thanks

2018-11-12 09:46 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
Thanks, good point. If this is overriden, the very "core" will be changed.

Changed.

2018-11-12 09:50 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public DeleteFinalMessageProcessor(PlatformTransactionManager transactionManager) {
Well, good question, was thinking about it as well. Relates to the PR https://github.com/OpenWiseSolutions/openhub-framework/pull/93 

It should be the transactionManager that manages openhub datasource. Which one is that? In proposition of https://github.com/OpenWiseSolutions/openhub-framework/pull/93 it is either Spring-Boot autoconfigured one (then only one is present), or the Primary bean, if multiple beans are present.

Hence wiring with the interface only, not with qualifier or anything.

2018-11-12 09:53 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +public class DeleteFinalMessageProcessor implements FinalMessageProcessor {
It is, however it is registered in Configuration class - see FinalMessageProcessingConfiguration, motivation was to register it only if this whole functionality is enabled

2018-11-12 11:23 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/DeleteFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
@pjuza  thanks for mentioning it, DeleteFinalMessageProcessor is now ConditionalOnMissing bean, meaning it can be overriden easily, not just with Primary bean. Then you can simple achieve different behaviour with your custom FinalMessageProcessor.

However I think in most cases, custom implementation will want to delete the messages ultimately. Just implement custom "archiving" before that. That is achievable with the listener only. Listener has some control as well, meaning, if it throws exception, delete will not continue. That way it could hopefully ensure, that messages won´t be lost unexpectedly.

2018-11-12 11:25 UTC, kkovarik commented on core-api/src/main/java/org/openhubframework/openhub/api/asynch/finalmessage/FinalMessageProcessor.java
> + * to be processed by this processor. After this, they should not be in OpenHub datastore
Thanks, good point, updated javadoc.

2018-11-12 11:30 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +/*
Thanks, added

2018-11-12 11:33 UTC, kkovarik commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC = PREFIX + "asynch.finalMessages.ok.saveTimeInSec";
Setting to '0' means, that messages will be processed as soon as possible. Effectively meaning next scheduled job run,

Javadoc improved, thanks good idea to pointing that out.

2018-11-14 11:18 UTC, kkovarik commented
Updated implementation & description. Now there is job, service and collection of FinalMessageProcessors. One of the MessageProcessor is DeleteFinalMessageProcessor. Please check PR again.

2018-11-17 07:26 UTC, pjuza commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC = PREFIX + "asynch.finalMessages.ok.saveTimeInSec";
And what value should I use if I want to have specific messages forever in data store?

2018-11-17 07:26 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +        FINAL_MSG_STATES_CONFIG.put(MsgStateEnum.OK, CoreProps.ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC);
I would throw exception during startup ...

2018-11-17 07:39 UTC, pjuza approved these changes

2018-11-17 07:39 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingJob.java
> +    public final void processFinalMessages() {
I would appreacite if I could disable job at all. Maybe also with some configuration parameter ...
I would use the same parameter you already have: org.openhubframework.openhub.api.configuration.CoreProps#ASYNCH_FINAL_MESSAGES_PROCESSING_ENABLED

2018-11-17 07:39 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +                    LOG.warn("Failed to process message : {}, will continue with next.", message, ex);
I think it's "normal" error => please change log level to error.

2018-11-17 07:39 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/AbstractFinalMessageProcessor.java
> +    public void processMessage(final Message message) {
this method should be final

2018-11-17 07:39 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/AbstractFinalMessageProcessor.java
> +
I would add logging on level DEBUG/TRACE ...

2018-11-17 07:39 UTC, pjuza commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessageProcessingConfiguration.java
> +import org.springframework.beans.factory.annotation.Qualifier;
Unused imports ...

2018-11-17 07:45 UTC, pjuza commented
Please dont't forget to add new wiki page - I prefer to add new page under 
https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/33573/User+guide. It's quite new feature :)

2018-11-19 08:45 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingJob.java
> +    public final void processFinalMessages() {
It is already implemented that way. Job is not on packageScan, it is registered as bean conditionaly in the configuration class **org.openhubframework.openhub.core.common.asynch.finalmessage.FinalMessageProcessingConfiguration**

idea is that none if this beans (job, service, processor) is registered, if the property  ASYNCH_FINAL_MESSAGES_PROCESSING_ENABLED is false

2018-11-19 08:48 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessageProcessingConfiguration.java
> +import org.springframework.beans.factory.annotation.Qualifier;
Thanks!

2018-11-19 09:02 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/FinalMessagesProcessingServiceImpl.java
> +                    LOG.warn("Failed to process message : {}, will continue with next.", message, ex);
Changed

2018-11-19 10:56 UTC, kkovarik commented on core/src/main/java/org/openhubframework/openhub/core/common/asynch/finalmessage/AbstractFinalMessageProcessor.java
> +
Thanks for mentioning it, added logging to AbstractFinalMessageProcessor and added seting MDC Log context in FinalMessageProcessingService, so that logs of message processing are correlated via correlationId.

2018-11-19 12:04 UTC, kkovarik commented
Added documentation https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/778764295/Messages+in+final+state and configuration described in https://openhubframework.atlassian.net/wiki/spaces/OHF/pages/33599/OpenHub+configuration

2018-11-19 12:40 UTC, kkovarik commented on core-api/src/main/java/org/openhubframework/openhub/api/configuration/CoreProps.java
> +    public static final String ASYNCH_FINAL_MESSAGES_OK_SAVE_TIME_IN_SEC = PREFIX + "asynch.finalMessages.ok.saveTimeInSec";
Added possibility to set value to "-1", then it will be kept indefinitely

2018-11-20 07:39 UTC, pjuza commented
My last two comments to AbstractFinalMessageProcessor - I would change logging level to trace from debug because often there is huge amount of messages and I would add add final to processMessage method.
I like your solution!

2018-11-21 09:23 UTC, kkovarik commented
Log level changed & processMessage not final

2018-11-21 10:06 UTC, hanusto approved these changes

2018-11-21 11:05 UTC, merged